---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nsanssqv/fundamorserver2/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R index.js $DEPLOYPATH
    - /bin/cp -R app.js $DEPLOYPATH
    - /bin/cp -R package.json $DEPLOYPATH